# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

apiVersion: v1
kind: Service
metadata:
  name: akka-seed
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    run: akka-seed
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: akka-seed
  name: akka-seed
spec:
  serviceName: akka-seed
  replicas: 2
  selector:
    matchLabels:
      run: akka-seed
  template:
    metadata:
      labels:
        run: akka-seed
    spec:
      containers:
      - name: akka-seed
        image: saturnism/akka-cluster-example
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#        - name: BIND_HOST_NAME
#          valueFrom:
#            fieldRef:
#              apiVersion: v1
#              fieldPath: status.podIP
        - name: SEED_NODES
          value: akka-seed-1.akka-seed
        command: ["/bin/bash", "-c", 'test "${POD_NAME}" == "akka-seed-0" && timeout 1 bash -c "cat < /dev/null > /dev/tcp/akka-seed-1.akka-seed/2551" || export SEED_NODES="akka-seed-0.akka-seed,${SEED_NODES}"; HOST_NAME=${POD_NAME}.akka-seed java -jar /app/app.jar']
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
